# Gopkg.toml for dummyapp

# dep still doesn't handle build-tags and expanding out the various
# combinations, so any dependencies which rely upon tags and which
# we don't want to be lost, should be included here in 'required'.
#
# Note that dep still doesn't handle OS-specific dependencies, so
# if we run into those before dep gains support, then add support
# for calling dep to build/build.from-within-dockerfile.sh
#
required = [
  "go.pennock.tech/hmetrics",
  "github.com/sirupsen/logrus",
  "github.com/rs/zerolog",
  ]

# nb: AFAICT, dep might be failing to handle a leading 'v' in the git tag name
# when it comes to the ~ operator and falling back to equality of the part
# after the 'v'?  I should look into this properly and submit a bug report /
# patch.  (dep v0.4.1)
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.5"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "^1.5.0"

[[constraint]]
  name = "go.pennock.tech/hmetrics"
  version = "~0.1.0"

[prune]
  go-tests = true
  unused-packages = true

# https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-go
# Need at least value of `go list -e .` for root-package.
#
# Note: we don't use this in our normal flows, because we use Docker builds
# outside Heroku, but we add the data here to support a Heroku build flow.
[metadata.heroku]
  root-package = "go.pennock.tech/dummyapp"
  # go-version: accept their most-recent supported version
  # install: we're happy with `go install .`
  # ensure: don't set false, we do want `dep ensure` run
