name: Tag Checker

permissions: {}

on:
  push:
    tags:
      - '**'

jobs:
  tag-check:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      checks: write
      statuses: write

    steps:

      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          # We want to be able to push tag deletions if we reject it
          persist-credentials: true
          # By default, full tags get replaced by lightweight tags, unless we use ref: here to point to the explicit ref we are testing.
          ref: ${{ github.ref }}

      - id: key-imports
        name: Import keys
        shell: bash
        run: |2
          for ghUser in $GitHubSigningUsers; do
            curl -fSsL "https://github.com/$ghUser.gpg" | gpg --import || true
          done
        env:
          GitHubSigningUsers: "philpennock"

      - id: tag-check
        name: Tag Check
        shell: bash
        run: |2
          shopt -s extglob
          nuke() {
            echo "$1"
            git tag -d "$NEW_TAG"
            git push origin ":$NEW_TAG"
            exit 1
          }
          set -x
          tag_type="$(git cat-file -t -- "$FULL_TAG")"
          case "$tag_type" in
            commit)
              # Lightweight tag
              case "$NEW_TAG" in
                wip/* | wip-* | wip_* ) true ;;
                exp/* | exp-* | exp/* ) true ;;
                *)
                  git cat-file -p -- "$FULL_TAG"
                  nuke "::error title=Disallowed lightweight tag::tag ${NEW_TAG@Q} is lightweight and prohibited"
                  ;;
              esac
              ;;

            tag)
              signature="$(git tag -l --format='%(contents:signature)' -- "$NEW_TAG")"
              case "$NEW_TAG" in
                +([0-9.]) )
                  nuke "::error title=Tag version without v prefix::tag ${NEW_TAG@Q} looks like a version number but is missing a leading v"
                  ;;
                v+([0-9.]) )
                  if [[ -z "${signature:-}" ]]; then
                    nuke "::error title=Version tag is unsigned::tag ${NEW_TAG@Q} is a version tag but is unsigned"
                  fi
                  if ! git tag -v -- "$NEW_TAG"; then
                    nuke "::error title=Version tag bad signature::tag ${NEW_TAG@Q} is signed but not by a signer allowed by us"
                  fi
                  ;;
              esac
              ;;

            *)
              nuke "::error title=Unrecognised tag type::tag ${NEW_TAG@Q} has unrecognised type ${tag_type@Q}"
              ;;
          esac
        env:
          NEW_TAG: ${{ github.ref_name }}
          FULL_TAG: ${{ github.ref }}
